vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        video_games:
            uri_prefix: /images/video_games
            upload_destination: '%kernel.project_dir%/public/images/video_games'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
