name: QA

on: [push, pull_request]

jobs:
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2, cs2pr
          extensions: pdo, pgsql, pdo_pgsql

      - name: Setup Cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Caching dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.3-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php8.3-composer-latest-

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Check coding standards
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --stop-on-violation

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          extensions: pdo, pgsql, pdo_pgsql

      - name: Setup Cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Caching dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.3-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php8.3-composer-latest-

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src tests --level=10

  php-unit:
    name: PHPUnit
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          extensions: pdo, pgsql, pdo_pgsql

      - name: Setup Cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Caching dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.3-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php8.3-composer-latest-

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Run tests
        run: composer test
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/test?serverVersion=16&charset=utf8"